name: '🤔 Support or Usage Question'
description: Get help using ion-calendar.
labels:
- question
- needs-triage
body:
  - type: markdown
    attributes:
      value: 'Please read and follow the instructions before submitting an issue:'
  - type: markdown
    attributes:
      value: |
        - Read all our documentation, especially the [README](https://github.com/heliomarpm/ion-calendar/blob/master/README.md). It may contain information that helps you solve your issue.
        - Ensure your issue isn't already [reported](https://github.com/heliomarpm/ion-calendar/issues?utf8=%E2%9C%93&q=is%3Aissue).

  - type: markdown
    attributes:
      value: '⚠️👆 Feel free to these instructions before submitting the issue 👆⚠️'
  - type: textarea
    id: description
    attributes:
      label: 'Describe the issue'
      description: A clear and concise description of what the issue is.
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: 'Example Code'
      description: Code snippet to illustrate your question
      render: js
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: 'Expected behavior'
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: markdown
    attributes:
      value: Environment

  - type: input
    id: node-version
    attributes:
      label: 'Node.js Version'
      description: 'node --version'
      placeholder: 'e.g. 16.8.1'
  - type: input
    id: os
    attributes:
      label: 'OS'
      placeholder: 'e.g. iOS 16.0.2, OSX 12.6.0'
  - type: textarea
    id: other-version
    attributes:
      label: 'Additional Library Versions'
      placeholder: |
        e.g.
        Angular 16.0,
        Ionic 7.0.0
      render: bash
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context/Screenshots'
      description: Add any other context about the problem here. If applicable, add screenshots to help explain.
      render: bash
    validations:
      required: false
