# name: Publish
# on:
#   release:
#     types: [created]
name: Publish
on:
  push:
    tags: ["*"]
    paths:
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '>=16.8.0'
          registry-url: https://npm.pkg.github.com/
          # scope: "@heliomarpm"

      - name: Install dependencies
        run: npm ci

      # - name: Tests
      #   run: npm run test

      - name: Build
        run: npm run build

      - name: Publish
        run: |
          cd dist/ion-calendar
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
