name: Publish
# on:
#   release:
#     types: [created]
on:
  push:
    tags: ["*"]
    paths:
      - 'projects/ion-calendar/package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node NPM
        uses: actions/setup-node@v3
        with:
          node-version: '>=16.8.0'
          # registry-url: https://npm.pkg.github.com/
          registry-url: https://registry.npmjs.org/
          scope: "@heliomarpm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish NPM
        run: |
          cp README.md dist/ion-calendar
          cd dist/ion-calendar
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      # - name: Publish Lib
      #   uses: JS-DevTools/npm-publish@v2
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
      #     strategy: all


      - name: Setup Node GPR
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@heliomarpm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish GPR
        run: |
          cp README.md dist/ion-calendar
          cd dist/ion-calendar
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
